version: '3.8'

services:
  backend:
    build:
      context: ai-code-reviewer
      dockerfile: ai-code-reviewer/backend/Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ai-code-reviewer
      dockerfile: ai-code-reviewer/frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
